version: "3.9"

services:
  neo4j-test:
    image: neo4j:5.16.0-community
    ports:
      - "8687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test-password
    volumes:
      - "./tmp/neo4j-test:/neo4j"
