/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 0.0.0
 * source: platform/profile/v1/models.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../identity/v1/models";
import * as pb_1 from "google-protobuf";
export class Profile extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        identity?: dependency_1.Identity;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("identity" in data && data.identity != undefined) {
                this.identity = data.identity;
            }
        }
    }
    get identity() {
        return pb_1.Message.getWrapperField(this, dependency_1.Identity, 1) as dependency_1.Identity;
    }
    set identity(value: dependency_1.Identity) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get has_identity() {
        return pb_1.Message.getField(this, 1) != null;
    }
    static fromObject(data: {
        identity?: ReturnType<typeof dependency_1.Identity.prototype.toObject>;
    }): Profile {
        const message = new Profile({});
        if (data.identity != null) {
            message.identity = dependency_1.Identity.fromObject(data.identity);
        }
        return message;
    }
    toObject() {
        const data: {
            identity?: ReturnType<typeof dependency_1.Identity.prototype.toObject>;
        } = {};
        if (this.identity != null) {
            data.identity = this.identity.toObject();
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_identity)
            writer.writeMessage(1, this.identity, () => this.identity.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Profile {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Profile();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.identity, () => message.identity = dependency_1.Identity.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Profile {
        return Profile.deserialize(bytes);
    }
}
