// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file product/v2/product_service.proto (package product.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetProductRequest, GetProductResponse } from "./product_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service product.v2.ProductService
 */
export const ProductService = {
  typeName: "product.v2.ProductService",
  methods: {
    /**
     * @generated from rpc product.v2.ProductService.GetProduct
     */
    getProduct: {
      name: "GetProduct",
      I: GetProductRequest,
      O: GetProductResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

