// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: identity/v1/models.proto

package identityV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityProvider int32

const (
	IdentityProvider_UNSPECIFIED IdentityProvider = 0
	IdentityProvider_GOOGLE      IdentityProvider = 1
	IdentityProvider_GITHUB      IdentityProvider = 2
)

// Enum value maps for IdentityProvider.
var (
	IdentityProvider_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "GOOGLE",
		2: "GITHUB",
	}
	IdentityProvider_value = map[string]int32{
		"UNSPECIFIED": 0,
		"GOOGLE":      1,
		"GITHUB":      2,
	}
)

func (x IdentityProvider) Enum() *IdentityProvider {
	p := new(IdentityProvider)
	*p = x
	return p
}

func (x IdentityProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_v1_models_proto_enumTypes[0].Descriptor()
}

func (IdentityProvider) Type() protoreflect.EnumType {
	return &file_identity_v1_models_proto_enumTypes[0]
}

func (x IdentityProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityProvider.Descriptor instead.
func (IdentityProvider) EnumDescriptor() ([]byte, []int) {
	return file_identity_v1_models_proto_rawDescGZIP(), []int{0}
}

type GoogleProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email      string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	GivenName  string `protobuf:"bytes,4,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName string `protobuf:"bytes,5,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Picture    string `protobuf:"bytes,6,opt,name=picture,proto3" json:"picture,omitempty"`
	Locale     string `protobuf:"bytes,7,opt,name=locale,proto3" json:"locale,omitempty"`
}

func (x *GoogleProfile) Reset() {
	*x = GoogleProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_v1_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoogleProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleProfile) ProtoMessage() {}

func (x *GoogleProfile) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleProfile.ProtoReflect.Descriptor instead.
func (*GoogleProfile) Descriptor() ([]byte, []int) {
	return file_identity_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *GoogleProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GoogleProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GoogleProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoogleProfile) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *GoogleProfile) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *GoogleProfile) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *GoogleProfile) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type GithubProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Login     string `protobuf:"bytes,4,opt,name=login,proto3" json:"login,omitempty"`
	AvatarUrl string `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	HtmlUrl   string `protobuf:"bytes,6,opt,name=html_url,json=htmlUrl,proto3" json:"html_url,omitempty"`
	Location  string `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Bio       string `protobuf:"bytes,8,opt,name=bio,proto3" json:"bio,omitempty"`
}

func (x *GithubProfile) Reset() {
	*x = GithubProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_v1_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GithubProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubProfile) ProtoMessage() {}

func (x *GithubProfile) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubProfile.ProtoReflect.Descriptor instead.
func (*GithubProfile) Descriptor() ([]byte, []int) {
	return file_identity_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *GithubProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GithubProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GithubProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GithubProfile) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GithubProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *GithubProfile) GetHtmlUrl() string {
	if x != nil {
		return x.HtmlUrl
	}
	return ""
}

func (x *GithubProfile) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GithubProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type IdentityProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider     IdentityProvider `protobuf:"varint,2,opt,name=provider,proto3,enum=IdentityProvider" json:"provider,omitempty"`
	ProfileId    string           `protobuf:"bytes,3,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	ProfileEmail string           `protobuf:"bytes,4,opt,name=profile_email,json=profileEmail,proto3" json:"profile_email,omitempty"`
	// Types that are assignable to Profile:
	//
	//	*IdentityProfile_Google
	//	*IdentityProfile_Github
	Profile isIdentityProfile_Profile `protobuf_oneof:"profile"`
}

func (x *IdentityProfile) Reset() {
	*x = IdentityProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_v1_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProfile) ProtoMessage() {}

func (x *IdentityProfile) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityProfile.ProtoReflect.Descriptor instead.
func (*IdentityProfile) Descriptor() ([]byte, []int) {
	return file_identity_v1_models_proto_rawDescGZIP(), []int{2}
}

func (x *IdentityProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdentityProfile) GetProvider() IdentityProvider {
	if x != nil {
		return x.Provider
	}
	return IdentityProvider_UNSPECIFIED
}

func (x *IdentityProfile) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *IdentityProfile) GetProfileEmail() string {
	if x != nil {
		return x.ProfileEmail
	}
	return ""
}

func (m *IdentityProfile) GetProfile() isIdentityProfile_Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (x *IdentityProfile) GetGoogle() *GoogleProfile {
	if x, ok := x.GetProfile().(*IdentityProfile_Google); ok {
		return x.Google
	}
	return nil
}

func (x *IdentityProfile) GetGithub() *GithubProfile {
	if x, ok := x.GetProfile().(*IdentityProfile_Github); ok {
		return x.Github
	}
	return nil
}

type isIdentityProfile_Profile interface {
	isIdentityProfile_Profile()
}

type IdentityProfile_Google struct {
	Google *GoogleProfile `protobuf:"bytes,5,opt,name=google,proto3,oneof"`
}

type IdentityProfile_Github struct {
	Github *GithubProfile `protobuf:"bytes,6,opt,name=github,proto3,oneof"`
}

func (*IdentityProfile_Google) isIdentityProfile_Profile() {}

func (*IdentityProfile_Github) isIdentityProfile_Profile() {}

type Identity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Profile *IdentityProfile `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
}

func (x *Identity) Reset() {
	*x = Identity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_v1_models_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_models_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_identity_v1_models_proto_rawDescGZIP(), []int{3}
}

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetProfile() *IdentityProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_identity_v1_models_proto protoreflect.FileDescriptor

var file_identity_v1_models_proto_rawDesc = []byte{
	0x0a, 0x18, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb, 0x01, 0x0a, 0x0d, 0x47,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x69, 0x76, 0x65, 0x6e, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x69, 0x76, 0x65,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x22, 0xc7, 0x01, 0x0a, 0x0d, 0x47, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x74, 0x6d,
	0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x74, 0x6d,
	0x6c, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62,
	0x69, 0x6f, 0x22, 0xf3, 0x01, 0x0a, 0x0f, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x28, 0x0a, 0x06, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x47, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x06, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x06, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x42, 0x09, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x46, 0x0a, 0x08, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x2a, 0x3b, 0x0a, 0x10, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x4f, 0x4f, 0x47, 0x4c, 0x45, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x49, 0x54, 0x48, 0x55, 0x42, 0x10, 0x02, 0x42, 0x3d, 0x5a,
	0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x69, 0x71, 0x75,
	0x65, 0x65, 0x6e, 0x2f, 0x62, 0x65, 0x73, 0x74, 0x6f, 0x2f, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x67,
	0x6f, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x76,
	0x31, 0x3b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_identity_v1_models_proto_rawDescOnce sync.Once
	file_identity_v1_models_proto_rawDescData = file_identity_v1_models_proto_rawDesc
)

func file_identity_v1_models_proto_rawDescGZIP() []byte {
	file_identity_v1_models_proto_rawDescOnce.Do(func() {
		file_identity_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_identity_v1_models_proto_rawDescData)
	})
	return file_identity_v1_models_proto_rawDescData
}

var file_identity_v1_models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_identity_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_identity_v1_models_proto_goTypes = []interface{}{
	(IdentityProvider)(0),   // 0: IdentityProvider
	(*GoogleProfile)(nil),   // 1: GoogleProfile
	(*GithubProfile)(nil),   // 2: GithubProfile
	(*IdentityProfile)(nil), // 3: IdentityProfile
	(*Identity)(nil),        // 4: Identity
}
var file_identity_v1_models_proto_depIdxs = []int32{
	0, // 0: IdentityProfile.provider:type_name -> IdentityProvider
	1, // 1: IdentityProfile.google:type_name -> GoogleProfile
	2, // 2: IdentityProfile.github:type_name -> GithubProfile
	3, // 3: Identity.profile:type_name -> IdentityProfile
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_identity_v1_models_proto_init() }
func file_identity_v1_models_proto_init() {
	if File_identity_v1_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_identity_v1_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoogleProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_v1_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GithubProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_v1_models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_v1_models_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_identity_v1_models_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*IdentityProfile_Google)(nil),
		(*IdentityProfile_Github)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_identity_v1_models_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_v1_models_proto_goTypes,
		DependencyIndexes: file_identity_v1_models_proto_depIdxs,
		EnumInfos:         file_identity_v1_models_proto_enumTypes,
		MessageInfos:      file_identity_v1_models_proto_msgTypes,
	}.Build()
	File_identity_v1_models_proto = out.File
	file_identity_v1_models_proto_rawDesc = nil
	file_identity_v1_models_proto_goTypes = nil
	file_identity_v1_models_proto_depIdxs = nil
}
